# Generated by Django 5.2.4 on 2026-03-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
