# Generated by Django 5.2.4 on 2026-03-10 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_stockrecord_is_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockrecord",
            name="is_public",
        ),
    ]
