# Generated by Django 5.2.4 on 2026-03-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stockrecord_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
