# Generated by Django 5.2.4 on 2026-03-19 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockrecord_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount'),
        ),
    ]
