# Generated by Django 5.2.4 on 2026-04-12 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0005_stockrecord_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrecord",
            name="offer_discount",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Offer Discount",
            ),
        ),
    ]
