# Generated by Django 5.2.4 on 2026-04-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_stockrecord_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='sold',
            field=models.IntegerField(default=0, verbose_name='Sold'),
        ),
    ]
