# Generated by Django 5.2.4 on 2026-04-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stockrecord_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10, verbose_name='status'),
        ),
    ]
