# Generated by Django 5.2.4 on 2026-04-20 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0009_stockrecord_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockrecord",
            name="is_public",
        ),
    ]
