# Generated by Django 5.2.17 on 2026-09-26 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0023_product_seller"),
        ("stock", "0010_remove_stockrecord_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockrecord",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_record",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
    ]
