# Generated by Django 5.2.17 on 2026-09-26 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0011_alter_stockrecord_product"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stockrecord",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="stockrecord",
            name="seller",
        ),
    ]
