# Generated by Django 5.2.4 on 2026-03-27 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_submited'),
        ('coupon', '0003_couponapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponapplication',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='cart'),
        ),
    ]
