# Generated by Django 5.2.4 on 2026-04-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupon", "0005_couponapplication_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="active",
        ),
        migrations.AddField(
            model_name="coupon",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("suspended", "Suspended"),
                ],
                default="active",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
