# Generated by Django 5.2.17 on 2026-09-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("one_time", "One-time Payment"),
                    ("subscription", "Subscription"),
                    ("installment", "Installment"),
                ],
                default="one_time",
                max_length=20,
            ),
        ),
    ]
