# Generated by Django 5.2.17 on 2026-09-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0006_payment_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_checkout_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
