# Generated by Django 5.2.17 on 2026-09-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0007_payment_stripe_checkout_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_event_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
