# Generated by Django 5.2.4 on 2026-04-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0018_alter_product_short_description'),
        ('stock', '0008_stockrecord_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_class/', verbose_name='image')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='catalog.category', verbose_name='categories')),
                ('product_classes', models.ManyToManyField(to='catalog.productclass', verbose_name='product classes')),
                ('stock_records', models.ManyToManyField(to='stock.stockrecord', verbose_name='stock records')),
            ],
            options={
                'verbose_name': 'Product List',
                'verbose_name_plural': 'Product Lists',
            },
        ),
        migrations.CreateModel(
            name='CollectionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_class/', verbose_name='image')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='catalog.category', verbose_name='categories')),
                ('product_lists', models.ManyToManyField(to='collection.productlist', verbose_name='product lists')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
    ]
