# Generated by Django 5.2.4 on 2026-04-20 14:31

from django.db import migrations, models

import collection.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0018_alter_product_short_description"),
        ("collection", "0001_initial"),
        ("stock", "0009_stockrecord_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionlist",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="catalog.category", verbose_name="categories"
            ),
        ),
        migrations.AlterField(
            model_name="collectionlist",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=collection.models.upload_to_class_name,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="collectionlist",
            name="name",
            field=models.CharField(max_length=250, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="collectionlist",
            name="product_lists",
            field=models.ManyToManyField(
                blank=True, to="collection.productlist", verbose_name="product lists"
            ),
        ),
        migrations.AlterField(
            model_name="productlist",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="catalog.category", verbose_name="categories"
            ),
        ),
        migrations.AlterField(
            model_name="productlist",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=collection.models.upload_to_class_name,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="productlist",
            name="name",
            field=models.CharField(max_length=250, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="productlist",
            name="product_classes",
            field=models.ManyToManyField(
                blank=True, to="catalog.productclass", verbose_name="product classes"
            ),
        ),
        migrations.AlterField(
            model_name="productlist",
            name="stock_records",
            field=models.ManyToManyField(
                blank=True, to="stock.stockrecord", verbose_name="stock records"
            ),
        ),
    ]
