# Generated by Django 5.2.4 on 2026-04-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collectionlist_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionlist',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='productlist',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='short description'),
        ),
    ]
