# Generated by Django 5.2.4 on 2026-03-10 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0003_offertype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "open"), ("Suspended", "Suspended")],
                        default="open",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="The highest priority offers are applied first",
                        verbose_name="Priority",
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="When an offer has given more discount to orders than this threshold, then the offer becomes unavailable",
                        max_digits=10,
                        null=True,
                        verbose_name="Max discount",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Offers are active from the start date. Leave this empty if the offer has no start date.",
                        null=True,
                        verbose_name="Start date",
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Offers are active until the end date. Leave this empty if the offer has no expiry date.",
                        null=True,
                        verbose_name="End date",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date Updated"),
                ),
                (
                    "offer_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="offer.offertype",
                        verbose_name="Offer Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "offer",
                "verbose_name_plural": "offers",
                "ordering": ["-priority", "pk"],
            },
        ),
    ]
