# Generated by Django 5.2.4 on 2026-04-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0005_alter_offer_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="desc_header",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Description Header"
            ),
        ),
    ]
