# Generated by Django 5.2.4 on 2026-04-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_offer_desc_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offer/', verbose_name='Image'),
        ),
    ]
