# Generated by Django 5.2.4 on 2026-04-12 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0007_offer_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offertype",
            name="value",
        ),
        migrations.AddField(
            model_name="offertype",
            name="max_discount",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Max Discount",
            ),
        ),
    ]
