# Generated by Django 5.2.4 on 2026-04-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0008_remove_offertype_value_offertype_max_discount"),
        ("stock", "0006_stockrecord_offer_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offerrange",
            name="excluded_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="exclude_product_ranges",
                to="stock.stockrecord",
                verbose_name="Excluded Products",
            ),
        ),
        migrations.AlterField(
            model_name="offerrange",
            name="included_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="product_ranges",
                to="stock.stockrecord",
                verbose_name="Included Products",
            ),
        ),
    ]
