# Generated by Django 5.2.4 on 2026-03-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('customer', 'Customer')], default='customer', max_length=10, verbose_name='Type'),
        ),
    ]
