# Generated by Django 5.2.4 on 2026-04-10 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
