# Generated by Django 5.2.4 on 2026-04-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                null=True, upload_to="users", verbose_name="Profile Image"
            ),
        ),
    ]
