# Generated by Django 5.2.4 on 2026-03-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="First name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Last name"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=255, verbose_name="City"),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Province/State"
                    ),
                ),
                ("country", models.CharField(blank=True, verbose_name="country")),
                (
                    "postcode",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Post/Zip-code"
                    ),
                ),
                ("address", models.TextField(verbose_name="address")),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
    ]
