# Generated by Django 5.2.4 on 2026-03-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_address_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IR", "Iran"),
                    ("US", "United States"),
                    ("CA", "Canada"),
                    ("UK", "United Kingdom"),
                    ("AU", "Australia"),
                ],
                verbose_name="country",
            ),
        ),
    ]
