# Generated by Django 5.2.4 on 2026-04-10 18:21

from django.db import migrations

import address.fields


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0006_alter_address_address_type_alter_address_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="phone_number",
            field=address.fields.PhoneNumberField(
                max_length=20, verbose_name="Phone Number"
            ),
        ),
    ]
