# Generated by Django 5.2.4 on 2026-04-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_alter_address_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('IR', 'Iran'), ('US', 'United States'), ('CA', 'Canada'), ('UK', 'United Kingdom'), ('AU', 'Australia'), ('GER', 'Germany')], verbose_name='country'),
        ),
    ]
