# Generated by Django 5.2.4 on 2026-02-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_product_slug_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
