# Generated by Django 5.2.4 on 2026-03-01 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_product_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattributevalue",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_attributes",
                to="catalog.product",
                verbose_name="product",
            ),
        ),
    ]
