# Generated by Django 5.2.4 on 2026-03-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_productattributevalue_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='value_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datetime'),
        ),
    ]
