# Generated by Django 5.2.4 on 2026-03-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productattributevalue_value_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
