# Generated by Django 5.2.4 on 2026-03-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_public',
        ),
    ]
