# Generated by Django 5.2.4 on 2026-04-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_userrating_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=200, null=True, verbose_name='Brand'),
        ),
    ]
