# Generated by Django 5.2.4 on 2026-04-13 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_product_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortDescriptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=250, verbose_name="title"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_descriptions",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
            ],
        ),
    ]
