# Generated by Django 5.2.4 on 2026-04-13 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_shortdescriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortdescriptions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalog.product', verbose_name='product'),
        ),
    ]
