# Generated by Django 5.2.4 on 2026-04-14 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_alter_shortdescriptions_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="product_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="catalog.productclass",
                verbose_name="product type",
            ),
        ),
    ]
