# Generated by Django 5.2.4 on 2026-04-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0017_productattributevalue_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Short Description"
            ),
        ),
    ]
