# Generated by Django 5.2.4 on 2026-04-21 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0019_remove_product_categories_product_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categories",
            new_name="category",
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
    ]
