# Generated by Django 5.2.4 on 2026-04-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0021_remove_product_product_class_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(max_length=100, null=True, verbose_name="color"),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(max_length=100, null=True, verbose_name="Brand"),
        ),
    ]
