# Generated by Django 5.2.17 on 2026-09-27 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0023_product_seller"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userrating",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_user_product_rating"
            ),
        ),
    ]
