# Generated by Django 5.2.4 on 2026-03-15 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Cart", "verbose_name_plural": "Carts"},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={"verbose_name": "Cart Item", "verbose_name_plural": "Cart Items"},
        ),
    ]
