# Generated by Django 5.2.4 on 2026-04-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('', ''), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='', max_length=1, verbose_name='rating'),
        ),
    ]
