# Generated by Django 5.2.4 on 2026-04-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('visible', 'Visible')], default='visible', max_length=7, verbose_name='status'),
        ),
    ]
