# Generated by Django 5.2.4 on 2026-04-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0003_comment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="rating",
            field=models.CharField(
                choices=[
                    ("0", ""),
                    ("1", "*"),
                    ("2", "**"),
                    ("3", "***"),
                    ("4", "****"),
                    ("5", "*****"),
                ],
                default="",
                max_length=1,
                verbose_name="rating",
            ),
        ),
    ]
