# Generated by Django 5.2.4 on 2026-04-13 21:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0005_reviewlike_comment_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReviewLike",
            new_name="ReviewReaction",
        ),
    ]
