# Generated by Django 5.2.4 on 2026-04-14 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_rename_reviewlike_reviewreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreaction',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reactions', to='comment.comment', verbose_name='review'),
        ),
    ]
