# Generated by Django 5.2.17 on 2026-09-26 14:19

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipping",
            name="delivery_time",
            field=models.CharField(max_length=250, verbose_name="Delivery Time"),
        ),
        migrations.AlterField(
            model_name="shipping",
            name="free_shipping_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Free Shipping Threshold",
            ),
        ),
        migrations.AlterField(
            model_name="shipping",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="shipping",
            name="shipping_type",
            field=models.CharField(
                choices=[("standard", "Standard"), ("express", "Express")],
                max_length=10,
                verbose_name="Shipping Type",
            ),
        ),
    ]
